# Generated by Django 4.2.7 on 2023-11-16 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=123)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1234)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.block')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=123)),
                ('status_room', models.CharField(choices=[('пустой', 'пустой'), ('бронирование', 'бронирование'), ('продано', 'продано')], default='пустой', max_length=123)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.floor')),
            ],
        ),
    ]
