# Generated by Django 4.2.7 on 2023-11-17 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_amountskidki_roomdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdetails',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.room'),
        ),
    ]
