# Generated by Django 4.2.7 on 2023-11-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_price_roomdetails_price_0_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomdetails',
            old_name='terrace_price',
            new_name='terrace_price_0',
        ),
        migrations.AddField(
            model_name='roomdetails',
            name='terrace_price_100',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roomdetails',
            name='terrace_price_30',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roomdetails',
            name='terrace_price_50',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
