# Generated by Django 4.2.7 on 2023-12-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_terrace_price_roomdetails_terrace_price_0_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomdetails',
            name='price_0',
        ),
        migrations.RemoveField(
            model_name='roomdetails',
            name='terrace_price_0',
        ),
        migrations.AlterField(
            model_name='room',
            name='status_room',
            field=models.CharField(choices=[('пустой', 'пустой'), ('бронирование', 'бронирование'), ('продано', 'продано'), ('не_продаже', 'не_продаже')], default='пустой', max_length=123),
        ),
    ]
